# https://travis-ci.org/HearthSim/hsarchetypes
language: python
python: "3.6"

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox

script:
  - tox

jobs:
  include:
    - stage: test

      cache:
        directories:
          - $HOME/.cache/pip
          - $TRAVIS_BUILD_DIR/.tox

      install:
        - pip install tox

      script:
        - tox

    - stage: deploy
      python: "2.7"
      env: ""
      if: branch = master AND type = push
      script: curl -X POST $BUILDTRIGGER_URL
